resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/4c48d34fd60991bb1b9168d293cfe31a975d858e/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test

extra-deps:
  - tasty-hedgehog-1.0.0.1

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  - generic-monoid-0.1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 4c48d34fd60991bb1b9168d293cfe31a975d858e
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 84d7978baf99443a0d74b6485feda598f9bc98f6
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 458324852cd1b68bfff35f30ee3a1298b736f106
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 6ea969b31c2bbaa7ba78b8e83b53a36bedfae10e
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 6e3047f785efe874819e8654ab928b0d9e9ff499
    subdirs:
      - contra-tracer

  # Not yet in Stack
  - bimap-0.4.0

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: ec96c64c665b741c17b4e38f611315bae9b0b054

  - Unique-0.4.7.6

nix:
  shell-file: nix/stack-shell.nix
